#!/bin/bash
#apt-get update
#apt-get install -y build-essential chrpath git-core libssl-dev libfontconfig1-dev libxft-dev
#git clone git://github.com/ariya/phantomjs.git
#cd phantomjs
#git checkout 1.9 -y
#./build.sh
apt-get update
apt-get install -y build-essential chrpath libssl-dev libxft-dev
apt-get install -y libfreetype6 libfreetype6-dev
apt-get install -y libfontconfig1 libfontconfig1-dev
cd ~
export PHANTOM_JS="phantomjs-1.9.8-linux-x86_64"
wget http://www.mylnikov.org/files/data/$PHANTOM_JS.tar.bz2
mv $PHANTOM_JS.tar.bz2 /usr/local/share/
cd /usr/local/share/
tar xvjf $PHANTOM_JS.tar.bz2
ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/share/phantomjs
ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/bin/phantomjs
ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/bin/phantomjs


#cd ~
#wget https://phantomjs.googlecode.com/files/phantomjs-1.9.2-linux-x86_64.tar.bz2
#tar xvjf phantomjs-1.9.2-linux-x86_64.tar.bz2
#cd phantomjs-1.9.2-linux-x86_64
#sudo ln -sf `pwd`/bin/phantomjs /usr/local/bin/phantomjs
#phantomjs --version
